// try {
//   let a = 0;
//   console.log(program);
//   console.log("Program ran successfully");
// } catch (error) {
//   console.log("this is an error");
// } finally {
//   console.log("I am a good boy");
// }

console.log("********************");

// try {
//   let a = 0;
//   console.log("Program ran successfully");
// } catch (error) {
//   console.log("this is an error");
// } finally {
//   console.log("I am a good boy");
// }

// console.log("********************");

// try {
//   let a = 0;
//   console.log(program);
//   console.log("Program ran successfully");
// } catch (error) {
//   console.log("this is an error");
//   console.log(p);
// } finally {
//   console.log("I am a good boy");
// }

console.log("********************");

try {
  let a = 0;
  console.log(program);
  console.log("Program ran successfully");
} catch (error) {
  console.log("this is an error");
  console.log(p);
}

console.log("I am a good boy"); // this will not be printed (without finally)
