// try {
//   let a = 0;
//   console.log("Program ran successfully");
// } catch (error) {
//   console.log("this is an error");
// }

console.log("**************************");

try {
  let a = 0;
  console.log(program);
  console.log("Program ran successfully");
} catch (error) {
  console.log("this is an error");
}
